#!/usr/bin/env bash
# Installs MySQL version 5.7
echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | sudo tee -a /etc/apt/sources.list
sudo apt-get update
sudo apt-get -y install mysql-server-5.7
